config/routes.rb
Rails.application.routes.draw do

  resources :contacts

  
	namespace :api do
	  resources :contacts
	end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/controllers/api/base_controller.rb
module Api
  class BaseController < ApplicationController
    protect_from_forgery with: :null_session
    before_action :set_resource, only: [:destroy, :show, :update]
    respond_to :json


	# POST /api/{plural_resource_name}
	def create
	  set_resource(resource_class.new(resource_params))

	  if get_resource.save
		render :show, status: :created
	  else
		render json: get_resource.errors, status: :unprocessable_entity
	  end
	end

	# DELETE /api/{plural_resource_name}/1
	def destroy
	  get_resource.destroy
	  head :no_content
	end

	# GET /api/{plural_resource_name}
	def index
	  plural_resource_name = "@#{resource_name.pluralize}"
	  resources = resource_class.where(query_params)
#								.page(page_params[:page])
#								.per(page_params[:page_size])

	  instance_variable_set(plural_resource_name, resources)
	  respond_with instance_variable_get(plural_resource_name)
	end

	# GET /api/{plural_resource_name}/1
	def show
	  respond_with get_resource
	end

	# PATCH/PUT /api/{plural_resource_name}/1
	def update
	  if get_resource.update(resource_params)
		render :show
	  else
		render json: get_resource.errors, status: :unprocessable_entity
	  end
	end

    private

      # Returns the resource from the created instance variable
      # @return [Object]
      def get_resource
        instance_variable_get("@#{resource_name}")
      end

      # Returns the allowed parameters for searching
      # Override this method in each API controller
      # to permit additional parameters to search on
      # @return [Hash]
      def query_params
        {}
      end

      # Returns the allowed parameters for pagination
      # @return [Hash]
      def page_params
        params.permit(:page, :page_size)
      end

      # The resource class based on the controller
      # @return [Class]
      def resource_class
        @resource_class ||= resource_name.classify.constantize
      end

      # The singular name for the resource class based on the controller
      # @return [String]
      def resource_name
        @resource_name ||= self.controller_name.singularize
      end

      # Only allow a trusted parameter "white list" through.
      # If a single resource is loaded for #create or #update,
      # then the controller for the resource must implement
      # the method "#{resource_name}_params" to limit permitted
      # parameters for the individual model.
      def resource_params
        @resource_params ||= self.send("#{resource_name}_params")
      end

      # Use callbacks to share common setup or constraints between actions.
      def set_resource(resource = nil)
        resource ||= resource_class.find(params[:id])
        instance_variable_set("@#{resource_name}", resource)
      end
  end
end

app/controllers/api/contacts_controller.rb
module Api
  class ContactsController < Api::BaseController

    private

	def contact_params
		params.require(:contact).permit(:name, :phone)
	end  

	def query_params
		# this assumes that an album belongs to an artist and has an :artist_id
		# allowing us to filter by this
		params.permit(:name, :phone)
	end

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

# default view 
  def index
    @contacts = Contact.all
  end

	def new
  		@contact = Contact.new
	end

	def edit
  		@contact = Contact.find(params[:id])
	end
	

		
	def create
		@contact = Contact.new(contact_params)
		if @contact.save
		  redirect_to @contact
		else
		  # This line overrides the default rendering behavior, which
		  # would have been to render the "create" view.
		  render "new"
    	end
  	end

  def show
    @contact = Contact.find(params[:id])
  end
  
  def update
    @contact = Contact.find(params[:id])
    @contact.update!(contact_params)
    redirect_to "index"
  end
 
  private
    # Using a private method to encapsulate the permissible parameters
    # is just a good pattern since you'll be able to reuse the same
    # permit list between create and update. Also, you can specialize
    # this method with per-user checking of permissible attributes.
    def contact_params
      params.require(:contact).permit(:name, :phone)
    end  
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/edit.html.erb
<h1>New Contact</h1>
<!-- form accept-charset="UTF-8" action="/contacts" method="post">
  <input type="text" name="contact[name]" value="Maneesh" />
  <input type="text" name="contact[phone]" value="949-683-1434" />
</form -->


<%= form_for @contact do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :phone %>
  <input type="submit" value="submit" /> 
<% end %>

app/views/contacts/index.html.erb
<h2>Listing Contacts</h2>
 
<%= link_to "New Contact", new_contact_path %>

<table>
  <tr>
    <th>Name</th>
    <th>Phone</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 
<% @contacts.each do |contact| %>
  <tr>
    <td><%= contact.name %></td>
    <td><%= contact.phone %></td>
    <td><%= link_to "Show", contact %></td>
    <td><%= link_to "Edit", edit_contact_path(contact) %></td>
    <td><%= link_to "Remove", contact, method: :delete, data: { confirm: "Are you sure?" } %></td>
  </tr>
<% end %>
</table>
 
<br>
 

app/views/contacts/new.html.erb
<h1>New Contact</h1>
<!-- form accept-charset="UTF-8" action="/contacts" method="post">
  <input type="text" name="contact[name]" value="Maneesh" />
  <input type="text" name="contact[phone]" value="949-683-1434" />
</form -->


<%= form_for @contact do |f| %>
  <%= f.text_field :name %>
  <%= f.text_field :phone %>
  <input type="submit" value="submit" /> 
<% end %>

app/views/contacts/show.html.erb
<h1>Listing Contacts</h1>

<%= link_to "All Contacts", contact_path %>
<%= link_to "New Contact", new_contact_path %>
 
<table>
  <tr>
    <th>id</th>
    <th>Name</th>
    <th>Phone</th>
  </tr>
 
  <tr>
    <td><%= @contact.id %></td>
    <td><%= @contact.name %></td>
    <td><%= @contact.phone %></td>
  </tr>
</table>
 
<br>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>